language: java
jdk: oraclejdk8

branches:
  only:
    - vending-machine-api
script:
  - ./mvnw clean install -B
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api-key:
   secure: $HEROKU_API_KEY
  app:
   branch: vending-machine-api